const SWITCH_TO_CONNECTED = "SWITCH_TO_CONNECTED";
const SWITCH_TO_DISCONNECTED = "SWITCH_TO_DISCONNETED";
const SWITCH_TO_INPROGRESS = "SWITCH_TO_DISCONNSWITCH_TO_INPROGRESSTED";
const SWITCH_TO_ERROR = "SWITCH_TO_ERROR";
const SWITCH_TO_ABORTED = "SWITCH_TO_ABORTED";

export { SWITCH_TO_CONNECTED, SWITCH_TO_DISCONNECTED, SWITCH_TO_ERROR, SWITCH_TO_INPROGRESS, SWITCH_TO_ABORTED };
