const SET_BUBBLE = "SET_BUBBLE";
const UPDATE_PROGRESS = "UPDATE_PROGRESS";
const UPDATE_CANCELED = "UPDATE_CANCELED";
const UPDATE_COMPLETED = "UPDATE_COMPLETED";
const UPDATE_ERROR = "UPDATE_ERROR";
const UPDATE_START = "UPDATE_START";

export { SET_BUBBLE, UPDATE_PROGRESS, UPDATE_CANCELED, UPDATE_COMPLETED, UPDATE_ERROR, UPDATE_START };
